@authorization = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6InRlc3QifSwiaWF0IjoxNjIxOTMzOTM1LCJleHAiOjE2MjI1Mzg3MzV9.tM7689V4kNhgG2h0VUSS5rN3tJYcUHJ8Kwsos4Nl6cE


### 添加一个书签
POST /api/bookmarkAdd HTTP/1.1
Host: localhost:2000
Content-Type: application/json
authorization: {{authorization}}

{
    "tagId": 1,
    "tagName": "zhou,xiang,i,f",
    "title": "zhouxiang",
    "url": "zhouxiang234"
}

### 拿到指定id的书签
GET /api/bookmark?id=1
Host: localhost:2000
connection: keep-alive
origin: chrome-extension://egljlaiibdecbiaekcinpimidnighcbn
authorization: {{authorization}}
###
POST /api/userLogin
Host: localhost:2000
Content-Type: application/json
connection: keep-alive
origin: chrome-extension://egljlaiibdecbiaekcinpimidnighcbn

{
    "username": "test",
    "password": "123456"
}

### 通过tagId获得书签列表
GET /api/bookmarksByTag?tagId=12
Host: localhost:2000
connection: keep-alive
origin: chrome-extension://egljlaiibdecbiaekcinpimidnighcbn
authorization: {{authorization}}

### 获得一段文字的关键字
POST /api/getKeyword
Content-Type: application/json
Host: localhost:2000
connection: keep-alive
origin: chrome-extension://egljlaiibdecbiaekcinpimidnighcbn
authorization: {{authorization}}

{
    "text": "贾跃亭的 FF 91 大升级：声控 27 英寸超大显示屏、后排能躺平"
}