@authorization = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6InRlc3QifSwiaWF0IjoxNjM3MDQ1OTEzLCJleHAiOjE2Mzc2NTA3MTN9.i_Cd0PGTHAjstWxsyaJXNecCODZBV4e7eT7lSHjAKo0


### 添加一个书签
POST /api/bookmarkAdd HTTP/1.1
Host: localhost:2000
Content-Type: application/json
authorization: {{authorization}}

{
    "tagId": "1,2,3,4",
    "tagName": "zhou,xiang,i,pp",
    "title": "zhouxiang",
    "url": "test for reinsert"
}

### 拿到指定id的书签
GET /api/bookmark?id=42
Host: localhost:2000
connection: keep-alive
origin: chrome-extension://egljlaiibdecbiaekcinpimidnighcbn
authorization: {{authorization}}


### 拿取指定url的书签
GET /api/bookmarkByUrl/?url=https://debug.mxplay.com/debug/get_details/
Host: localhost:2000
connection: keep-alive
origin: chrome-extension://egljlaiibdecbiaekcinpimidnighcbn
authorization: {{authorization}}


###
POST /api/userLogin
Host: localhost:2000
Content-Type: application/json
connection: keep-alive
origin: chrome-extension://egljlaiibdecbiaekcinpimidnighcbn

{
    "username": "test",
    "password": "123456"
}

### 通过tagId获得书签列表
GET /api/bookmarksByTag?tagId=12
Host: localhost:2000
connection: keep-alive
origin: chrome-extension://egljlaiibdecbiaekcinpimidnighcbn
authorization: {{authorization}}

### 获得一段文字的关键字
POST /api/getKeyword
Content-Type: application/json
Host: localhost:2000
connection: keep-alive
origin: chrome-extension://egljlaiibdecbiaekcinpimidnighcbn
authorization: {{authorization}}

{
    "text": "贾跃亭的 FF 91 大升级：声控 27 英寸超大显示屏、后排能躺平"
}